#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logMain)
Q_DECLARE_LOGGING_CATEGORY(logCipher)
Q_DECLARE_LOGGING_CATEGORY(logClient)
Q_DECLARE_LOGGING_CATEGORY(logDeviceService)
Q_DECLARE_LOGGING_CATEGORY(logGuiService)
Q_DECLARE_LOGGING_CATEGORY(logRegistry)
Q_DECLARE_LOGGING_CATEGORY(logServer)
Q_DECLARE_LOGGING_CATEGORY(logService)
Q_DECLARE_LOGGING_CATEGORY(logSocketThread)
Q_DECLARE_LOGGING_CATEGORY(logUpdater)
Q_DECLARE_LOGGING_CATEGORY(logDatabase)
Q_DECLARE_LOGGING_CATEGORY(logWindowsHooks)
Q_DECLARE_LOGGING_CATEGORY(logEventFilter)

#endif // LOGGINGCATEGORIES_H
