#include "loggingcategories.h"

Q_LOGGING_CATEGORY(logMain,            "Main")
Q_LOGGING_CATEGORY(logCipher,          "Cipher")
Q_LOGGING_CATEGORY(logClient,          "Client")
Q_LOGGING_CATEGORY(logDeviceService,   "DeviceService")
Q_LOGGING_CATEGORY(logGuiService,      "GuiService")
Q_LOGGING_CATEGORY(logRegistry,        "Registry")
Q_LOGGING_CATEGORY(logServer,          "Server")
Q_LOGGING_CATEGORY(logService,         "Service")
Q_LOGGING_CATEGORY(logSocketThread,    "SocketThread")
Q_LOGGING_CATEGORY(logUpdater,         "Updater")
Q_LOGGING_CATEGORY(logDatabase,        "Database")
Q_LOGGING_CATEGORY(logWindowsHooks,    "WindowsHooks")
Q_LOGGING_CATEGORY(logEventFilter,     "EventFilter")
